name: home_service_app
description: A home service app similar to Urban Company

# The following version string is used for this example. Adjust it for your project.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^5.0.0
  provider: ^6.0.0
  # Image handling
  cached_network_image: ^3.0.0
  # Optional for animations and visual appeal
  flutter_spinkit: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following section lists assets such as images, fonts, etc.
  assets:
    - assets/images/plumbing.jpeg
    - assets/images/electrical.jpeg
    - assets/images/cleaning.jpg
    - assets/images/painting.jpg
    # Add more images as needed, or remove unused ones

  uses-material-design: true

# Enable web support (if you want to target Flutter Web)
web:
  renderer: canvaskit

# Optional: fonts
# Uncomment and add any fonts you want to include in the app
# fonts:
#   - family: OpenSans
#     fonts:
#       - asset: assets/fonts/OpenSans-Regular.ttf
#       - asset: assets/fonts/OpenSans-Bold.ttf
#         weight: 700
